services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sinso\Variables\:
    resource: '../Classes/*'

  Sinso\Variables\Hooks\DataHandler:
    public: true

  Sinso\Variables\Hooks\ContentProcessor:
    tags:
      - name: event.listener

  Sinso\Variables\Service\VariablesService:
    public: true

  Sinso\Variables\EventListener\ModifyCacheLifetime:
    tags:
      - name: event.listener
