services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sinso\Variables\:
    resource: '../Classes/*'

  Sinso\Variables\Hooks\DataHandler:
    public: true

  Sinso\Variables\Service\VariablesService:
    public: true
